version: "3.7"
services:
  api_service:
    build: ./users/
    restart: always
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - my-net
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true'
      SPRING_DATASOURCE_USERNAME: '$MYSQLDB_USER'
      SPRING_DATASOURCE_PASSWORD: '$MYSQLDB_PASSWORD'
      #SPRING_PROPERTIES_HIBERNATE: 'org.hibernate.dialect.MySQLDialect'
      SPRING_DDL_AUTO: 'update'
      SERVER_PORT: '8082'
      HOST_SMTP: '$HOST_SMTP'
      PORT_SMTP: '$PORT_SMTP'
      USER_SMTP: '$USER_SMTP'
      PASSWORD_SMTP: '$PASSWORD_SMTP'
    depends_on:
      - mysqldb
    
    volumes:
      - .m2:/root/.m2
      
  mysqldb:
    build: ./
    image: "mysql:latest"
    restart: always
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - my-net  
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
networks:
  my-net: