FROM maven:3.8.3-openjdk-17 AS build
# Establece el directorio de trabajo en /API_REST_U/users
WORKDIR /API_REST_U/users
# Copia el código fuente y el archivo pom.xml
COPY src ./src
COPY pom.xml .
# Ejecuta el comando Maven para construir el archivo JAR
RUN mvn clean package -DskipTests
# Lista los archivos en el directorio target
RUN ls -l target
FROM openjdk:17-jdk-alpine
# Crea un usuario y un grupo para ejecutar la aplicación
RUN addgroup -S spring && adduser -S spring -G spring
# Establece el usuario que ejecutará la aplicación
USER spring:spring
# Establece el argumento JAR_FILE para el archivo JAR generado
ARG JAR_FILE=/API_REST_U/users/target/*.jar
# Copia el archivo JAR generado desde la etapa de construcción
COPY --from=build $JAR_FILE app.jar
# Ejecuta la aplicación al iniciar el contenedor
ENTRYPOINT ["java", "-jar", "/app.jar"]